import accounts_close_raw from './accounts_close.js';
import accounts_create_raw from './accounts_create.js';
import accounts_delete_raw from './accounts_delete.js';
import accounts_get_balance_raw from './accounts_get_balance.js';
import accounts_list_raw from './accounts_list.js';
import accounts_reopen_raw from './accounts_reopen.js';
import accounts_update_raw from './accounts_update.js';
import bank_sync_raw from './bank_sync.js';
import budget_updates_batch_raw from './budget_updates_batch.js';
import budgets_get_all_raw from './budgets_get_all.js';
import budgets_getMonth_raw from './budgets_getMonth.js';
import budgets_getMonths_raw from './budgets_getMonths.js';
import budgets_holdForNextMonth_raw from './budgets_holdForNextMonth.js';
import budgets_resetHold_raw from './budgets_resetHold.js';
import budgets_setAmount_raw from './budgets_setAmount.js';
import budgets_setCarryover_raw from './budgets_setCarryover.js';
import budgets_transfer_raw from './budgets_transfer.js';
import categories_create_raw from './categories_create.js';
import categories_delete_raw from './categories_delete.js';
import categories_get_raw from './categories_get.js';
import categories_update_raw from './categories_update.js';
import category_groups_create_raw from './category_groups_create.js';
import category_groups_delete_raw from './category_groups_delete.js';
import category_groups_get_raw from './category_groups_get.js';
import category_groups_update_raw from './category_groups_update.js';
import payee_rules_get_raw from './payee_rules_get.js';
import payees_create_raw from './payees_create.js';
import payees_delete_raw from './payees_delete.js';
import payees_get_raw from './payees_get.js';
import payees_merge_raw from './payees_merge.js';
import payees_update_raw from './payees_update.js';
import query_run_raw from './query_run.js';
import rules_create_raw from './rules_create.js';
import rules_create_or_update_raw from './rules_create_or_update.js';
import rules_delete_raw from './rules_delete.js';
import rules_get_raw from './rules_get.js';
import rules_update_raw from './rules_update.js';
import server_info_raw from './server_info.js';
import transactions_create_raw from './transactions_create.js';
import transactions_delete_raw from './transactions_delete.js';
import transactions_filter_raw from './transactions_filter.js';
import transactions_get_raw from './transactions_get.js';
import transactions_import_raw from './transactions_import.js';
import transactions_search_by_amount_raw from './transactions_search_by_amount.js';
import transactions_search_by_category_raw from './transactions_search_by_category.js';
import transactions_search_by_month_raw from './transactions_search_by_month.js';
import transactions_search_by_payee_raw from './transactions_search_by_payee.js';
import transactions_summary_by_category_raw from './transactions_summary_by_category.js';
import transactions_summary_by_payee_raw from './transactions_summary_by_payee.js';
import transactions_uncategorized_raw from './transactions_uncategorized.js';
import transactions_update_raw from './transactions_update.js';
import transactions_update_batch_raw from './transactions_update_batch.js';
import session_close_raw from './session_close.js';
import session_list_raw from './session_list.js';
import meta_registry_raw from './meta_registry.js';
import meta_tool_call_raw from './meta_tool_call.js';

// Conditional imports: search tools only exposed when SEARCH_ENABLED !== 'false'
const searchEnabled = (process.env.SEARCH_ENABLED ?? 'true') !== 'false';
const hybrid_search_raw = searchEnabled
  ? (await import('./hybrid_search.js')).default
  : null;
const search_similar_raw = searchEnabled
  ? (await import('./search_similar.js')).default
  : null;
const search_index_info_raw = searchEnabled
  ? (await import('./search_index_info.js')).default
  : null;

export const accounts_close = accounts_close_raw;
export const accounts_create = accounts_create_raw;
export const accounts_delete = accounts_delete_raw;
export const accounts_get_balance = accounts_get_balance_raw;
export const accounts_list = accounts_list_raw;
export const accounts_reopen = accounts_reopen_raw;
export const accounts_update = accounts_update_raw;
export const bank_sync = bank_sync_raw;
export const budget_updates_batch = budget_updates_batch_raw;
export const budgets_get_all = budgets_get_all_raw;
export const budgets_getMonth = budgets_getMonth_raw;
export const budgets_getMonths = budgets_getMonths_raw;
export const budgets_holdForNextMonth = budgets_holdForNextMonth_raw;
export const budgets_resetHold = budgets_resetHold_raw;
export const budgets_setAmount = budgets_setAmount_raw;
export const budgets_setCarryover = budgets_setCarryover_raw;
export const budgets_transfer = budgets_transfer_raw;
export const categories_create = categories_create_raw;
export const categories_delete = categories_delete_raw;
export const categories_get = categories_get_raw;
export const categories_update = categories_update_raw;
export const category_groups_create = category_groups_create_raw;
export const category_groups_delete = category_groups_delete_raw;
export const category_groups_get = category_groups_get_raw;
export const category_groups_update = category_groups_update_raw;
export const payee_rules_get = payee_rules_get_raw;
export const payees_create = payees_create_raw;
export const payees_delete = payees_delete_raw;
export const payees_get = payees_get_raw;
export const payees_merge = payees_merge_raw;
export const payees_update = payees_update_raw;
export const query_run = query_run_raw;
export const rules_create = rules_create_raw;
export const rules_create_or_update = rules_create_or_update_raw;
export const rules_delete = rules_delete_raw;
export const rules_get = rules_get_raw;
export const rules_update = rules_update_raw;
export const server_info = server_info_raw;
export const transactions_create = transactions_create_raw;
export const transactions_delete = transactions_delete_raw;
export const transactions_filter = transactions_filter_raw;
export const transactions_get = transactions_get_raw;
export const transactions_import = transactions_import_raw;
export const transactions_search_by_amount = transactions_search_by_amount_raw;
export const transactions_search_by_category = transactions_search_by_category_raw;
export const transactions_search_by_month = transactions_search_by_month_raw;
export const transactions_search_by_payee = transactions_search_by_payee_raw;
export const transactions_summary_by_category = transactions_summary_by_category_raw;
export const transactions_summary_by_payee = transactions_summary_by_payee_raw;
export const transactions_uncategorized = transactions_uncategorized_raw;
export const transactions_update = transactions_update_raw;
export const transactions_update_batch = transactions_update_batch_raw;
// Only export search tools when search is enabled — ActualToolsManager
// skips entries without a `name` property, so null is effectively hidden.
export const hybrid_search = hybrid_search_raw;
export const search_similar = search_similar_raw;
export const search_index_info = search_index_info_raw;
export const session_close = session_close_raw;
export const session_list = session_list_raw;
export const meta_registry = meta_registry_raw;
export const meta_tool_call = meta_tool_call_raw;
